use crate::db::Database;
use crate::models::task::Task;
use chrono::NaiveDate;
use std::sync::Arc;

pub struct InsightService {
    db: Arc<Database>,
    ai_service: Arc<super::ai_service::AIService>,
}

impl InsightService {
    pub fn new(db: Arc<Database>, ai_service: Arc<super::ai_service::AIService>) -> Self {
        Self { db, ai_service }
    }
    
    pub async fn generate_daily_insight(&self, date: NaiveDate) -> Result<String, String> {
        let tasks = self.get_tasks_by_date(date)?;
        
        let completed = tasks.iter().filter(|t| t.status == crate::models::task::TaskStatus::Completed).count();
        let total = tasks.len();
        let completion_rate = if total > 0 {
            (completed as f32 / total as f32) * 100.0
        } else {
            0.0
        };
        
        let prompt = format!(
            "根据 {} 的任务数据生成复盘报告：\n总任务: {}\n已完成: {}\n完成率: {:.1}%\n\n请生成一份简洁的 Markdown 格式日报，包含：\n1. 今日总结\n2. 完成情况分析\n3. 明日建议",
            date,
            total,
            completed,
            completion_rate
        );
        
        let insight = self.ai_service.generate_summary(&prompt).await?;
        
        let report = format!(
            "# 📅 {} 任务复盘\n\n## 📊 统计\n- 总任务: {}\n- 已完成: {}\n- 完成率: {:.1}%\n\n## 📝 AI 洞察\n{}\n\n---\n*Generated by Nexus AI*",
            date,
            total,
            completed,
            completion_rate,
            insight
        );
        
        self.save_insight(date, &report).await?;
        
        Ok(report)
    }
    
    fn get_tasks_by_date(&self, date: NaiveDate) -> Result<Vec<Task>, String> {
        let date_str = date.to_string();
        let conn = self.db.get_connection();
        let conn = conn.lock().map_err(|e| e.to_string())?;
        
        let mut stmt = conn
            .prepare(
                "SELECT * FROM tasks WHERE DATE(created_at) = DATE(?1)"
            )
            .map_err(|e: rusqlite::Error| e.to_string())?;
        
        let tasks = stmt.query_map([&date_str], |row: &rusqlite::Row| {
            let entities_str: String = row.get::<_, String>("extracted_entities")?;
            let extracted_entities = if entities_str.is_empty() {
                None
            } else {
                Some(entities_str.split(", ").map(|s| s.to_string()).collect())
            };
            
            Ok(Task {
                id: row.get("id")?,
                content: row.get("content")?,
                extracted_datetime: row.get("extracted_datetime")?,
                extracted_entities,
                event: row.get("event")?,
                priority: match row.get::<_, i32>("priority")? {
                    0 => crate::models::task::Priority::Low,
                    1 => crate::models::task::Priority::Medium,
                    _ => crate::models::task::Priority::High,
                },
                status: match row.get::<_, String>("status")?.as_str() {
                    "completed" => crate::models::task::TaskStatus::Completed,
                    "cancelled" => crate::models::task::TaskStatus::Cancelled,
                    _ => crate::models::task::TaskStatus::Pending,
                },
                created_at: row.get("created_at")?,
                completed_at: row.get("completed_at")?,
                updated_at: row.get("updated_at")?,
                reason: row.get("reason")?,
                topic_id: row.get("topic_id")?,
            })
        }).map_err(|e: rusqlite::Error| e.to_string())?;
        
        tasks.collect::<Result<Vec<_>, rusqlite::Error>>().map_err(|e: rusqlite::Error| e.to_string())
    }
    
    async fn save_insight(&self, date: NaiveDate, content: &str) -> Result<(), String> {
        use std::fs;
        use tauri::api::path::document_dir;
        
        let docs_dir = document_dir().ok_or("Failed to get documents dir")?;
        let nexus_dir = docs_dir.join("Nexus/reports");
        fs::create_dir_all(&nexus_dir).map_err(|e| e.to_string())?;
        
        let filename = nexus_dir.join(format!("{}_daily.md", date));
        fs::write(filename, content).map_err(|e| e.to_string())?;
        
        Ok(())
    }
}
